source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HNVideoImport_Example', :exclusive => true do
  pod "HNVideoImport", :path => "../"
end

target 'HNVideoImport_Tests', :exclusive => true do
  pod "HNVideoImport", :path => "../"

  
end
